sudo: required

services:
  - docker

env:
  global:
    - NAME=phusion/baseimage
    # - VERSION=$(TRAVIS_TAG)
    - VERSION=$(TRAVIS_BRANCH)

before_install:
  - docker build -t $(NAME):$(VERSION) --rm image
  - env NAME=$(NAME) VERSION=$(VERSION) ./test/runner.sh

after_success:
  - docker login -u "$(DOCKER_USERNAME)" -p "$(DOCKER_PASSWORD)";
    docker push $(NAME):$(VERSION);

# after_success:
#   - if [ "$(TRAVIS_BRANCH)" == "master" ]; then
#     docker login -u "$(DOCKER_USERNAME)" -p "$(DOCKER_PASSWORD)";
#     docker tag $(NAME):$(VERSION) $(NAME):latest
#     docker push $(NAME):$(VERSION);
#     fi
